# Generated by Django 5.2.13 on 2026-05-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DailyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='아기사자', max_length=80)),
                ('headline_eyebrow', models.CharField(default='ABOUT', max_length=80)),
                ('headline', models.CharField(default='안녕하세요, 아기사자예요.', max_length=120)),
                ('role_line', models.CharField(default='Frontend engineer · 서울 · she/her', max_length=160)),
                ('bio_ko', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('avatar_initials', models.CharField(default='BL', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('blurb', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('live', 'Live'), ('wip', 'In progress'), ('archive', 'Archived')], default='live', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분', max_length=300)),
                ('external_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField()),
                ('published_at', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='blog.dailycategory')),
            ],
            options={
                'verbose_name_plural': 'Daily entries',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='blog.profile')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('skills', models.CharField(help_text='쉼표로 구분', max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_groups', to='blog.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='영문 부제', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Markdown-lite. h2는 ## 로 시작')),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('series_label', models.CharField(blank=True, help_text='ex. series 5/8', max_length=80)),
                ('views', models.PositiveIntegerField(default=0)),
                ('license', models.CharField(default='CC BY 4.0', max_length=50)),
                ('published_at', models.DateField()),
                ('edited_at', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tech_posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40)),
                ('body', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.techpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
